
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 28 20:16:22 CDT 2014
//----------------------------------------------------

package Intermedio;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AS = 22;
  public static final int CIERRA_BODY = 10;
  public static final int INCLUDE_ONCE = 51;
  public static final int ENDDECLARE = 35;
  public static final int IMPLEMENTS = 49;
  public static final int CONST = 27;
  public static final int CIERRA_HEAD = 6;
  public static final int CALLABLE = 23;
  public static final int EVAL = 41;
  public static final int INTERROGACION = 19;
  public static final int ISSET = 55;
  public static final int DIFERENTE = 90;
  public static final int REQUIRE = 60;
  public static final int CATCH = 25;
  public static final int ENDSWITCH = 39;
  public static final int ABRE_PHP = 8;
  public static final int CERRARPAR = 79;
  public static final int ANDBOOLEANO = 92;
  public static final int THROW = 65;
  public static final int REQUIRE_ONCE = 61;
  public static final int ABRIRPAR = 78;
  public static final int DECLARE = 29;
  public static final int DECLARA = 16;
  public static final int INSTEADOF = 53;
  public static final int YIELD = 72;
  public static final int ABRE_BODY = 7;
  public static final int PROTECTED = 58;
  public static final int NOT = 17;
  public static final int ELSEIF = 99;
  public static final int ARRAY = 21;
  public static final int MENQUE = 85;
  public static final int VAR = 70;
  public static final int FINAL = 44;
  public static final int GOTO = 48;
  public static final int ABRE_HEAD = 3;
  public static final int MAYQUE = 86;
  public static final int PCOMA = 80;
  public static final int ENDWHILE = 40;
  public static final int EMPTY = 34;
  public static final int CLASS = 75;
  public static final int INCLUDE = 50;
  public static final int COMA = 14;
  public static final int ABSTRACT = 74;
  public static final int SLASH = 84;
  public static final int ENDFOR = 36;
  public static final int IGUAL = 89;
  public static final int WHILE = 98;
  public static final int USE = 69;
  public static final int EXTENDS = 43;
  public static final int INTERFACE = 54;
  public static final int DOSPUNTOS = 18;
  public static final int SWITCH = 64;
  public static final int VARIABLE = 104;
  public static final int FOR = 100;
  public static final int DO = 32;
  public static final int ORBOOLEANO = 91;
  public static final int RETURN = 62;
  public static final int PUBLIC = 59;
  public static final int ELSE = 97;
  public static final int TRY = 67;
  public static final int ANDEQUAL = 15;
  public static final int BREAK = 101;
  public static final int ECHO = 33;
  public static final int INT = 103;
  public static final int CERRARLLA = 95;
  public static final int CIERRA_PHP = 9;
  public static final int CIERRA_HTML = 11;
  public static final int EOF = 0;
  public static final int ABRIRLLA = 94;
  public static final int PUNTO = 77;
  public static final int DIE = 31;
  public static final int ENDFOREACH = 37;
  public static final int DEFAULT = 30;
  public static final int SUMA = 81;
  public static final int PRINT = 76;
  public static final int FUNCTION = 46;
  public static final int ENDIF = 38;
  public static final int OR = 57;
  public static final int COMILLA = 13;
  public static final int MENIGU = 87;
  public static final int EXIT = 42;
  public static final int error = 1;
  public static final int RESTA = 82;
  public static final int UNSET = 68;
  public static final int CONTINUE = 28;
  public static final int IF = 96;
  public static final int LIST = 56;
  public static final int INSTANCEOF = 52;
  public static final int ABRIR_HTML = 2;
  public static final int MAYIGU = 88;
  public static final int MULTIPLICACION = 83;
  public static final int FOREACH = 45;
  public static final int CLONE = 26;
  public static final int HALTCOM = 73;
  public static final int GLOBAL = 47;
  public static final int ASIGNACION = 93;
  public static final int CASE = 24;
  public static final int GBAJO = 12;
  public static final int ABRE_TITLE = 4;
  public static final int STRING = 102;
  public static final int AND = 20;
  public static final int STATIC = 63;
  public static final int XOR = 71;
  public static final int TRAIT = 66;
  public static final int CIERRA_TITLE = 5;
}

